CREATE TABLE EMPLOYEE(
	Employee_id NUMBER PRIMARY KEY,
	Emp_type VARCHAR(20) NOT NULL,
	Address VARCHAR(50) NOT NULL,
	Gender CHAR(1) CHECK(Gender ='F' OR Gender ='M' OR Gender ='O'),
	Name VARCHAR(20) NOT NULL,
	Salary NUMBER NOT NULL,
	History VARCHAR(1000) NOT NULL,
	Mobile_no NUMBER(11) CONSTRAINT elevendigits CHECK(Mobile_no>=00000000001 
						AND Mobile_no<=99999999999)
);

CREATE TABLE RECEPTIONIST( 
        Emp_id NUMBER NOT NULL,
	Work_hour NUMBER(2) NOT NULL,
        FOREIGN KEY(Emp_id) REFERENCES EMPLOYEE(Employee_id) ON DELETE CASCADE
	);

CREATE TABLE NURSE(
	Emp_id NUMBER PRIMARY KEY ,
	Working_hour NUMBER(2) NOT NULL,
         FOREIGN KEY(Emp_id) REFERENCES EMPLOYEE(Employee_id) ON DELETE CASCADE
	);

CREATE TABLE ROOM
( 
	Room_no INTEGER PRIMARY KEY,
	Room_type CHAR(50) NOT NULL
);


CREATE TABLE DOCTOR(
	D_id NUMBER PRIMARY KEY,
	Qualification VARCHAR(50) NOT NULL,
	Specialist VARCHAR(20) NOT NULL,
	Name VARCHAR(20) NOT NULL,
	Room_no INTEGER NOT NULL,
	Emp_id NUMBER NOT NULL,
        FOREIGN KEY(Emp_id) REFERENCES EMPLOYEE(Employee_id) ON DELETE SET NULL,
        FOREIGN KEY(Room_no) REFERENCES ROOM(Room_no) ON DELETE SET NULL
);

CREATE TABLE RECORDS(
	Record_no NUMBER PRIMARY KEY,
	Appoinment_date DATE,
	Patient_info VARCHAR(100) NOT NULL
);


CREATE TABLE MAINTANCE(
	Record_no NUMBER,
	Emp_id NUMBER NOT NULL,
        PRIMARY KEY(Record_no,Emp_id),
        FOREIGN KEY(Emp_id) REFERENCES EMPLOYEE(Employee_id) ON DELETE SET NULL,
        FOREIGN KEY(Record_no) REFERENCES RECORDS(Record_no) ON DELETE CASCADE
);


CREATE TABLE GOVERNS(
	Room_no INTEGER,
	Emp_id NUMBER NOT NULL,
        PRIMARY KEY(Room_no,Emp_id),
        FOREIGN KEY(Emp_id) REFERENCES EMPLOYEE(Employee_id) ON DELETE SET NULL,
        FOREIGN KEY(Room_no) REFERENCES ROOM(Room_no) ON DELETE SET NULL
);


CREATE TABLE PATIENT
(
	Patient_id VARCHAR(50) PRIMARY KEY,
	Name CHAR(50) NOT NULL,
	Mobile_no INTEGER, 
	Sex CHAR(1) CHECK(Sex ='F' OR Sex ='M' OR Sex ='O') NOT NULL,
	Age INTEGER NOT NULL,
	Date_Of_Birth DATE
);	


CREATE TABLE ATTENDS
(
   Doc_id NUMBER,
   P_id VARCHAR(50),
   Time_period CHAR(50),
   PRIMARY KEY(Doc_id,P_id),
   FOREIGN KEY(Doc_id) REFERENCES DOCTOR(D_id) ON DELETE SET NULL,
   FOREIGN KEY(P_id) REFERENCES PATIENT(Patient_id) ON DELETE SET NULL
 );

CREATE TABLE TEST_REPORT
(
  Report_id VARCHAR(20) PRIMARY KEY,
  Prescription VARCHAR (50) NOT NULL,
  Description VARCHAR(1000)
);


CREATE TABLE MEDICINE
(
  Medicine_name VARCHAR(20) PRIMARY KEY,
  Quantity INTEGER NOT NULL,
  Price INTEGER NOT NULL,
  Medicine_type VARCHAR(30) NOT NULL,
  Shop_id VARCHAR(20)
);

 CREATE TABLE BILL
( 
  Bill_no FLOAT ,
  Med_name VARCHAR(20),
  Rep_id VARCHAR(20),
  P_id VARCHAR(50),
  Total_amount FLOAT,
  Date_of_bill DATE,
  PRIMARY KEY (Bill_no,Med_name,Rep_id, P_id),
  FOREIGN KEY(Med_name) REFERENCES MEDICINE(Medicine_name) ON DELETE SET NULL,
  FOREIGN KEY(Rep_id) REFERENCES TEST_REPORT(Report_id) ON DELETE SET NULL,
  FOREIGN KEY(P_id) REFERENCES PATIENT(Patient_id) ON DELETE SET NULL
); 

CREATE TABLE ALLOCATED
(
   P_id VARCHAR(50) PRIMARY KEY,
   Room_no INTEGER,
   FOREIGN KEY(P_id) REFERENCES  PATIENT(Patient_id) ON DELETE SET NULL
);
